version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"  # Map host port 5000 to container port 5000
    volumes:
      - ./backend:/app
      - ./backend/instance:/app/instance
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true